version : '3'
services :
  mysql :
    image : mysql:5.7.44
    container_name : quickstart-dev-jwt-auth-mysql
    restart : unless-stopped
    ports :
      - 3306:3306
    environment :
      - MYSQL_DATABASE=svc_testing_db
      - MYSQL_USER=svc_testing
      - MYSQL_PASSWORD=svc_testing
      - MYSQL_ROOT_PASSWORD=svc_root
      - TZ=UTC
  prometheus :
    container_name : quickstart-dev-jwt-auth-prometheus
    image : prom/prometheus:v2.54.1
    volumes :
      - ./src/main/docker/prometheus/:/etc/prometheus/
    command :
      - '--config.file=/etc/prometheus/prometheus.yml'
    # On MacOS, remove next line and replace localhost by host.docker.internal in src/main/docker/prometheus/prometheus.yml and
    # docker/grafana/provisioning/datasources/datasource.yml
    network_mode : 'host' # to test locally running service
  grafana :
    container_name : quickstart-dev-jwt-auth-grafana
    image : grafana/grafana:11.2.0
    volumes :
      - ./src/main/docker/grafana/provisioning/:/etc/grafana/provisioning/
    environment :
      - GF_SECURITY_ADMIN_PASSWORD=changeme
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    # On MacOS, remove next line and replace localhost by host.docker.internal in src/main/docker/prometheus/prometheus.yml and
    # docker/grafana/provisioning/datasources/datasource.yml
    network_mode : 'host' # to test locally running service
