spring :
  main :
    allow-circular-references : true
  application :
    name : basics-restful-jwt-auth
  datasource :
    type : com.zaxxer.hikari.HikariDataSource
    url : ${DATASOURCE_URL:jdbc:mysql://localhost:3306/sa_test_db?serverTimezone=UTC}
    username : ${DATASOURCE_USERNAME:sa_test}
    password : ${DATASOURCE_PASSWORD:sa_test}
    driver-class-name : ${DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
    hikari :
      pool-name : Hikari
      auto-commit : false
  jpa :
    hibernate :
      ddl-auto : none
      naming :
        physical-strategy : org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy : org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    open-in-view : true
    properties :
      hibernate.jdbc.time_zone : UTC
    show-sql : false

  jackson :
    default-property-inclusion : NON_NULL
  lifecycle :
    timeout-per-shutdown-phase : ${TIMEOUT_PER_SHUTDOWN:20s}

logging :
  level :
    ROOT : INFO
  pattern :
    console : "${spring.application.name} %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%X{transactionId},%X{traceId:-},%X{spanId:-}]){blue}[%thread] %clr(%-5level) %clr(%logger{36}){magenta} - %msg%n"

server :
  port : ${SERVER_PORT:8080}
  shutdown : graceful
logbook :
  exclude :
    - /actuator/**
    - /v3/**
    - /swagger-ui/**
    - /swagger-resources/**
    - /metrics
  filter :
    enabled : true
  format :
    style : json
  obfuscate :
    headers :
      - Authorization
      - X-Secret
    parameters :
      - access_token
      - password
  minimum-status : ${MINIMUM_STATUS_LOG_BODY:400}
management :
  server :
    add-application-context-header : true
  endpoints :
    enabled-by-default : false
    web :
      path-mapping :
        health : actuator/health
        prometheus : metrics
      base-path : /
      exposure :
        include : health, prometheus
  endpoint :
    health :
      enabled : true
    prometheus :
      enabled : true

jwt :
  token :
    secret : jwtapptokensecret
    expired : 3600000
